### ISSUE TITLE
Window.fetch: HEAD or GET Request cannot have a body for grafana versions > 6.6.2.

### ISSUE THREAD

**Issue by rjbgaspar** [camptocamp/grafana-prometheus-alertmanager-datasource#76] opened 2020-04-08 16:03 UTC
Hi,

For grafana versions greater than 6.6.2, it is not possible to get data from the camptocamp-prometheus-alertmanager-datasource. 

The following error is thrown on the http request
	Window.fetch:  HEAD or GET Request cannot have a body.

Thanks in advance.

Regards
Ricardo Gaspar

**Comment by dphilpot** [comment] 2020-04-08 16:07
Duplicate of https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/issues/72

@rjbgaspar there is also a PR which fixes this issue https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/pull/73

**Comment by yarix** [comment] 2020-06-01 16:04
same issue in version 7.0
![image](https://user-images.githubusercontent.com/6409857/83428191-9dc1be80-a43a-11ea-9077-afde8dea5f45.png)

**Closed** 2023-11-08 13:17 UTC
Labels: duplicate
