### ISSUE TITLE
Severity field is "blank" even though response has severity = "critical"

### ISSUE THREAD

**Issue by prashantsr** [camptocamp/grafana-prometheus-alertmanager-datasource#31] opened 2018-05-31 23:27 UTC
I've a panel with type table but severity column is blank. Is there a configuration on the datasource for severity?

**Comment by rk126** [comment] 2018-06-01 01:16
I am also seeing this issue, the prometheus alertmanager query response has the severity label key value pair present, but somehow the front end is getting messed up.

**Comment by cryptobioz** [comment] 2018-06-02 13:30
Are you using the latest version of the plugin? Did you define severity levels on the datasource configuration page (cf. #13)?

**Comment by VR6Pete** [comment] 2018-06-19 11:19
@cryptobioz the logic is flawed, what about for those with custom severity levels? 
I think it needs more flexibility for where this can be configured.

**Comment by rk126** [comment] 2018-06-19 20:46
@cryptobioz I did define the severity levels but realized that the latest release 0.0.5 doesn't have the fix #26 
There's a bug opened in Grafana as it is not able to use nested JSON data mentioned in our severity levels' datasource configuration.
With that keeping in mind, I tried out installing the master and still facing the difficulty as I am seeing an empty Severity column.

**Comment by rk126** [comment] 2018-06-19 20:53
I used the following configuration when I installed f6ccded (master top) version of this plugin.

{
        "name": "AlertManager",
        "type": "camptocamp-prometheus-alertmanager-datasource",
        "url":"http://...",
        "access": "proxy",
        "jsonData": {
            "severity_critical": "4",
            "severity_high": "3",
            "severity_info": "1",
            "severity_warning": "2"
        }
    }

**Comment by robshelly** [comment] 2018-10-17 10:29
Also seeing this issue. 
Provisioned the data source during installation using the followuing config:

```
    apiVersion: 1
    datasources:
    - name: AlertManager
      type: camptocamp-prometheus-alertmanager-datasource
      url: https://alertmanager.127.0.0.1.nip.io
      access: direct
      jsonData:
        timeInterval: 10s
        severity_critical: "4"
        severity_high: "3"
        severity_warning: "2"
        severity_info: "1"
```
Confirmed on the UI that the severity levels have been configured correctly.
Using the latest version of Grafana with the nested json issue [#26](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/issues/26) and [merged](https://github.com/grafana/grafana-plugin-repository/pull/286) to grafana-plugin-repository but still seeing blank severity fields in Grafana

**Comment by castronu** [comment] 2018-10-26 12:12
Hello everybody, I found a workaround:

In the dataource configuration (Severity Levels), i set:

Critical=critical
High=high
Warning=warning
Info=info

Then in Grafana Colum Styles options, I set "Type"=String and value mapping 1->info, 2-> Warning etc.

**Comment by VincenzoDo** [comment] 2018-11-14 12:57
Hello, I have a similar issue. When displaying alert on a table I can see the severity as long as I keep all fields of the table, if I specify "severity" then the column is displayed without value.
![image](https://user-images.githubusercontent.com/11388017/48483783-aa5cd280-e814-11e8-8e5d-360c9a12f629.png) and 
![image](https://user-images.githubusercontent.com/11388017/48483984-38d15400-e815-11e8-86e1-2fba64024738.png)

**Comment by cmeury** [comment] 2018-12-14 14:02
Can confirm, mentioning "severity" as a selected label will break this. 

One workaround is to explicitly define column styles for all columns you'd like to keep and then set `/.*/` to Hidden.

**Comment by michael-doubez** [comment] 2018-12-31 10:37
Got the same issue. The reason is that the "severity" column is hardcoded to be the one past the last column requested.

By example, if you request "instance,severity,alertname,summary", the generated row will be:

0. instance
1. empty (expected severity)
2. alertname
3. summary
4. unexpected severity value - not displayed because only 4 columns defined (+Time)

The fix is quite simple:
* don't filter severity but mark it as found at [datasource.js:119](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/blob/fb4c90018ee045723cfb8fca2a93bb64b6a52f38/src/datasource.js#L119)
* force severity as last column only if not found at [datasource.js:133](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/blob/fb4c90018ee045723cfb8fca2a93bb64b6a52f38/src/datasource.js#L133]

**Closed** 2019-01-21 15:12 UTC
Labels: bug

**Comment by cryptobioz** [comment] 2019-01-21 15:18
@michael-doubez Thanks for your help on this!

I'm thinking about to remove severity management from the datasource (#49), do you have any opinion on it?
